image: hamzael/django-test:latest

stages:
- test
- build

test:
  script:
    - cd ./djangonews; pytest

build:
  script:
    - docker build -t hamzael/djangonews-app ./djangonews
    - docker push hamzael/djangonews-app