version: '3'

services:
    web-server:
        build: ./web-server
        image: hamzael/djangonews-web
        ports:
            - 4433:443
        depends_on:
            - app-server
        volumes:
            - static_vol:/var/www/djangonews
    db-server:
        image: postgres:alpine
        env_file: ./db-server.env
        volumes:
            - db_vol:/var/lib/postgresql/data
    app-server:
        build: ./djangonews
        image: hamzael/djangonews-app
        depends_on:
            - db-server
        volumes:
            - static_vol:/var/www/djangonews

volumes:
    db_vol:
    static_vol:
