# Generated by Django 2.0.3 on 2018-04-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['published_at'],
            },
        ),
    ]
