# Generated by Django 2.0.3 on 2018-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
