# Generated by Django 2.0.3 on 2018-04-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
