# Generated by Django 2.0.3 on 2018-04-10 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20180410_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
