# Generated by Django 2.0.3 on 2018-04-10 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180410_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 13, 45, 34, 603926, tzinfo=utc)),
        ),
    ]
