# Generated by Django 2.0.3 on 2018-04-10 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20180410_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='nbr_upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 16, 19, 56, 895134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 16, 19, 56, 895792, tzinfo=utc)),
        ),
    ]
