# Generated by Django 2.0.3 on 2018-04-12 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0015_auto_20180412_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='nbr_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 17, 14, 13, 892055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 17, 14, 13, 891255, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 17, 14, 13, 892873, tzinfo=utc)),
        ),
    ]
