# Generated by Django 2.0.3 on 2018-04-13 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0019_auto_20180413_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 16, 18, 31, 462830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 16, 18, 31, 461759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 16, 18, 31, 463529, tzinfo=utc)),
        ),
    ]
