# Generated by Django 2.0.3 on 2018-04-30 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0025_auto_20180419_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 10, 37, 3, 1593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 10, 37, 3, 146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 10, 37, 3, 2774, tzinfo=utc)),
        ),
    ]
