FROM alpine:3.7

ENV SRC="/usr/src/djangonews" \
    STATIC_PATH="/var/www/djangonews/static" \
    USED_DOMAIN="app-server" \
    USING_HTTPS="yes" \
    DB_HOST="db-server" \
    DB_PORT="5432" \
    DJANGO_SECRET_KEY="XXXX" \
    SOCIAL_AUTH_FB_KEY="XXXX" \
    SOCIAL_AUTH_FB_SECRET="XXXX"

# Update and install python 3
RUN apk update && apk add python3 

# Create User & directories
RUN addgroup -S djangonews && \
    adduser -S -G djangonews djangonews && \
    mkdir -p $SRC && mkdir -p $STATIC_PATH && \
    chown -R djangonews:djangonews $SRC && chown -R djangonews:djangonews $STATIC_PATH

# Install other Packages
RUN apk add python3-dev gcc musl-dev postgresql-dev

# Copy Code
WORKDIR $SRC
COPY . .

# Install pip requirements
RUN pip3 install -r ./requirements.pip

USER djangonews

EXPOSE 8000

ENTRYPOINT ["ash", "./entry.sh"]
